import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = (props) => {
  const hello = api.example.hello.useQuery({ name: "from tRPC" });

  return (
    <>
      <Head>
        <title>Hello denizens of the world</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p className="flex h-screen items-center justify-center text-2xl text-black">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </p>
      </div>
    </>
  );
};

export default Home;
